import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import { GlobalProvider } from "./context/Auth";
import { Toaster } from "sonner";
import React from "react";
import { Content } from "./LoadingContent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalProvider>
          <Toaster richColors />
          <NavBar />
          <Content>{children}</Content>
        </GlobalProvider>
      </body>
    </html>
  );
}
